<script type="text/javascript"
        src="https://cdn.jsdelivr.net/npm/sweetalert2@7.32.4/dist/sweetalert2.all.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@7.29.2/dist/sweetalert2.min.css" type="text/css">


<?php
$est = new Zend_Session_Namespace('establecimiento');
$id_establecimiento = $est->establecimiento;

$idtipoev = new Zend_Session_Namespace('tipoevaluacion');
$idtevalucacion = $idtipoev->tipoevaluacion;


if ($id_establecimiento == 7) { ?>

    <link href="<?php echo $this->baseUrl; ?>/css/monitoreo.css" type="text/css" rel="stylesheet"/>
    <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreogreda_v3.js?v=1"></script>
    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php

        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso; ?>


            <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>


        <?php }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana">
                        <a class="button medium blue" id="nuevo"
                           href="<?php echo $this->url(array('controller' => 'Libro',
                               'action' => 'agregarguia', 'id' => ''), null, TRUE);
                           ?>"> Nueva Guía</a>
                    </div>

                    <div style="margin-top: 8%; margin-bottom: 7%;" class="center">
                        <h4>

                            <?php


                            // RQM 42
                            if (!is_null($this->listaasignatura[0]['idNucleo'])) {

                                ?>
                                <label for="ambito" class="required">Mostrar Núcleos por Ambito: </label>
                                <select name="idAmbito" style="width: 260px;" id="sltAmbito">
                                    <?php


                                    foreach ($this->listaambitos as $ambito) : ?>

                                        <option value="<?php echo $ambito['idAmbito']; ?>"><?php echo $ambito['nombreAmbito']; ?></option>
                                    <?php
                                    endforeach;

                                    ?>
                                </select>
                                <?php

                            }

                            ?>
                        </h4>
                    </div>

                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php


            // RQM 42
            if (!is_null($this->listaasignatura[0]['idNucleo'])) {

                foreach ($this->listaasignatura as $c) :

                    ?>

                    <li id="<?php echo $c['idAmbito']; ?>" class="asignaturali">
                        <a class="asignatura" href="#" id="<?php echo $c['idNucleo']; ?>" data-pre="true"
                           name="<?php echo $c['tipoAsignatura']; ?>"
                           data-idAmbito="<?php echo $c['idAmbito']; ?>"><?php echo $c['nombreNucleo']; ?>
                        </a>
                    </li>
                <?php
                endforeach;

            } else {
                foreach ($this->listaasignatura as $c) :
                ?>

                    <li>
                        <a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                           name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?>
                        </a>
                    </li>
                <?php
                endforeach;

            }


            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p style="margin: -4px !important;"><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>

                    <div id="alum" name="entregadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: green;">
                        <p style="color: white">Entregada </p>
                    </div>

                    <div id="alum" name="noentregadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: red;">
                        <p style="color: white">No Entregada </p>
                    </div>

                    <div id="alum" name="revisadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: cyan">
                        <p>Retroalimentada</p>
                    </div>

                    <div id="alum" name="revisainheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: yellow">
                        <p>Evaluada Formativamente </p>
                    </div>


                </div>

                <?php if ($idtevalucacion == 1) { ?>


                    <div class="grid-col primer" id="primer" style="display: none">
                        <div class="grid-item grid-item--header" style="background-color: #11b106;">
                            <p class="head">I SEM</p>
                        </div>
                        <?php /*foreach ($this->alumnos as $c) : */ ?>
                        <div class="grid-item sem">
                        </div>
                        <?php /*endforeach; */ ?>
                    </div>

                    <div class="grid-col segundo" id="segundo" style="display: none">
                        <div class="grid-item grid-item--header" style="background-color: #11b106;">
                            <p class="head">II SEM</p>
                        </div>
                        <?php /*foreach ($this->alumnos as $c) : */ ?>
                        <div class="grid-item sem">
                        </div>
                        <?php /*endforeach; */ ?>
                    </div>

                <?php } else { ?>

                    <div class="grid-col primer" id="primer" style="display: none">
                        <div class="grid-item grid-item--header" style="background-color: #11b106;">
                            <p class="head">I TRIM</p>
                        </div>
                        <?php /*foreach ($this->alumnos as $c) : */ ?>
                        <div class="grid-item sem">
                        </div>
                        <?php /*endforeach; */ ?>
                    </div>

                    <div class="grid-col segundo" id="segundo" style="display: none">
                        <div class="grid-item grid-item--header" style="background-color: #11b106;">
                            <p class="head">II TRIM</p>
                        </div>
                        <?php /*foreach ($this->alumnos as $c) : */ ?>
                        <div class="grid-item sem">
                        </div>
                        <?php /*endforeach; */ ?>
                    </div>

                    <div class="grid-col tercero" id="tercero" style="display: none">
                        <div class="grid-item grid-item--header" style="background-color: #11b106;">
                            <p class="head">III TRIM</p>
                        </div>
                        <?php /*foreach ($this->alumnos as $c) : */ ?>
                        <div class="grid-item sem">
                        </div>
                        <?php /*endforeach; */ ?>
                    </div>

                <?php } ?>


                <div class="grid-col grid-col--fixed-right" id="entregada"
                     style="width: 70px;right: 270px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: green; color: white">
                        <p class="head" style="color: white">Total Entregada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item entregada<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: green; color: white;">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

                <div class="grid-col grid-col--fixed-right" id="noentregada"
                     style="width: 70px;right: 200px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: red">
                        <p class="head" style="color: white">Total No Entregada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item noentregada<?php echo $c['idAlumnosActual']; ?> "
                             style="background-color: red">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

                <div class="grid-col grid-col--fixed-right" id="revisada"
                     style="width: 110px;right: 100px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: cyan">
                        <p class="head">Total Retroalimentada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item revisada<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: cyan">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>


                <div class="grid-col grid-col--fixed-right" id="revisadaincompleta"
                     style="width: 110px;right:0px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: yellow">
                        <p class="head">Total Evaluada Formativamente</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item revisadain<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: yellow; ">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

            </div>
        </div>


        <?php

    }


}//FIN LA GREDA

//INICIO CGV
else if ($id_establecimiento == 11) { ?>


    <link href="<?php echo $this->baseUrl; ?>/css/monitoreocgv.css" type="text/css" rel="stylesheet"/>
    <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreocgv.js"></script>

    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso;
            if ($ingresonota == 1) { ?>

                <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                    'action' => 'abrir', 'id' => $id_curso), null, TRUE);
                ?>"><i class="icon-hand-left"></i> Volver</a>

            <?php } else {
                ?>


                <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                    'action' => 'abrir', 'id' => $id_curso . '-' . $id_detalle_curso), null, TRUE);
                ?>"><i class="icon-hand-left"></i> Volver</a>

            <?php } ?>


            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>


        <?php }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>
            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>
        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana"><a class="button medium blue" id="nuevo"
                                            href="<?php echo $this->url(array('controller' => 'Libro',
                                                'action' => 'agregarguia', 'id' => ''), null, TRUE);
                                            ?>"> Nueva Guía</a></div>


                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php
            foreach ($this->listaasignatura as $c) : ?>

                <li><a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                       name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?></a></li>


            <?php endforeach;
            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>


                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p style="font-size: 18px">Total</p>
                    </div>


                </div>


                <div class="grid-col segundo" id="segundo" style="display: none">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">II SEM</p>
                    </div>
                    <?php /*foreach ($this->alumnos as $c) : */ ?>
                    <div class="grid-item sem">
                    </div>
                    <?php /*endforeach; */ ?>
                </div>


                <!--                <div class="grid-col grid-col--fixed-right" id="entregada"-->
                <!--                     style="width: 70px;right: 0px;background-color: whitesmoke">-->
                <!--                    <div class="grid-item grid-item--header final" style="background-color: green; color: white">-->
                <!--                        <p class="head" style="color: white">Total Entregada</p>-->
                <!--                    </div>-->
                <!--                    --><?php //foreach ($this->alumnos as $c) : ?>
                <!--                        <div class="grid-item entregada-->
                <?php //echo $c['idAlumnosActual']; ?><!--"-->
                <!--                             style="background-color: green; color: white;">-->
                <!--                            <p></p>-->
                <!--                        </div>-->
                <!--                    --><?php //endforeach; ?>
                <!---->
                <!---->
                <!--                </div>-->


            </div>
        </div>


        <?php

    }


} else if ($id_establecimiento == 14) { ?>

    <link href="<?php echo $this->baseUrl; ?>/css/monitoreo.css" type="text/css" rel="stylesheet"/>
    <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreohorcon.js"></script>
    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso; ?>


            <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>


        <?php }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>
            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>
        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana"><a class="button medium blue" id="nuevo"
                                            href="<?php echo $this->url(array('controller' => 'Libro',
                                                'action' => 'agregarguia', 'id' => ''), null, TRUE);
                                            ?>"> Nueva Guía</a></div>


                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php
            foreach ($this->listaasignatura as $c) : ?>

                <li><a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                       name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?></a></li>


            <?php endforeach;
            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>

                    <div id="alum" name="entregadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: pink;">
                        <p>Entregada </p>
                    </div>

                    <div id="alum" name="noentregadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: blue;">
                        <p style="color: white">No Entregada </p>
                    </div>

                    <div id="alum" name="revisadaheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: yellow">
                        <p>Retroalimentada</p>
                    </div>

                    <div id="alum" name="revisainheader" class="grid-item"
                         style="text-align: left; width: auto;background-color: darkgreen">
                        <p style="color:white;">Evaluada Formativamente </p>
                    </div>


                </div>

                <div class="grid-col primer" id="primer" style="display: none">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">I SEM</p>
                    </div>
                    <?php /*foreach ($this->alumnos as $c) : */ ?>
                    <div class="grid-item sem">
                    </div>
                    <?php /*endforeach; */ ?>
                </div>

                <div class="grid-col segundo" id="segundo" style="display: none">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">II SEM</p>
                    </div>
                    <?php /*foreach ($this->alumnos as $c) : */ ?>
                    <div class="grid-item sem">
                    </div>
                    <?php /*endforeach; */ ?>
                </div>


                <div class="grid-col grid-col--fixed-right" id="entregada"
                     style="width: 70px;right: 270px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: pink;">
                        <p class="head">Total Entregada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item entregada<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: pink;">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

                <div class="grid-col grid-col--fixed-right" id="noentregada"
                     style="width: 70px;right: 200px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: blue">
                        <p class="head" style="color: white">Total No Entregada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item noentregada<?php echo $c['idAlumnosActual']; ?> "
                             style="background-color: blue">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

                <div class="grid-col grid-col--fixed-right" id="revisada"
                     style="width: 110px;right: 100px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: yellow">
                        <p class="head">Total Retroalimentada</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item revisada<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: yellow">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>


                <div class="grid-col grid-col--fixed-right" id="revisadaincompleta"
                     style="width: 110px;right:0px;background-color: whitesmoke">
                    <div class="grid-item grid-item--header final" style="background-color: darkgreen">
                        <p style="color: white;" class="head">Total Evaluada Formativamente</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item revisadain<?php echo $c['idAlumnosActual']; ?>"
                             style="background-color: darkgreen">
                            <p></p>
                        </div>
                    <?php endforeach; ?>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>
                    <div class="grid-item" style="background-color: whitesmoke;">
                        <p></p>
                    </div>

                </div>

            </div>
        </div>


        <?php

    }

} else if ($id_establecimiento == 12) { ?>


    <link href="<?php echo $this->baseUrl; ?>/css/monitoreocesa.css" type="text/css" rel="stylesheet"/>
    <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreocesa_v3.1.js"></script>


    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;

        $codigos = new Zend_Session_Namespace('codigo');
        $codigo = $codigos->codigo;

        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso; ?>


            <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>


        <?php }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>
            <a class="button medium green" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'notasnuevo'), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Ir a Notas</a>
        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') { ?>

                    <div class="ventana"><a class="button medium blue" id="nuevo"
                                            href="<?php echo $this->url(array('controller' => 'Libro',
                                                'action' => 'agregarguianotas', 'id' => ''), null, TRUE);
                                            ?>"> Nueva Guía</a></div>


                <?php } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php
            foreach ($this->listaasignatura as $c) : ?>

                <li><a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                       name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?></a></li>


            <?php endforeach;
            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">

        <div class="grid-container" id="tblTabla">
            <div class="grid">
                <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                    <div class="grid-item grid-item--header">
                        <p class="head">Alumnos</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                             style="text-align: left; width: auto;">
                            <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                        </div>
                    <?php endforeach; ?>


                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p style="font-size: 18px">Total</p>
                    </div>


                </div>


                <div class="grid-col primer" id="primer">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">% Logro</p>
                        <p class="head">I Sem</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item sem porcentaje" name="<?php echo $c['idAlumnosActual']; ?>"
                             style="width: 62px">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>
                <div class="grid-col primerl" id="primerl">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">Nivel Logro</p>
                        <p class="head">I Sem</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item sem nivel" name="<?php echo $c['idAlumnosActual']; ?>">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>
                <div class="grid-col primern" id="primern">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">Nota Final</p>
                        <p class="head">I Sem</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item sem nota_final" name="<?php echo $c['idAlumnosActual']; ?>">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>


                <div class="grid-col segundo" id="segundo">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">% Logro</p>
                        <p class="head">II SEM</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item sem porcentaje_sem2" name="<?php echo $c['idAlumnosActual']; ?>"
                             style="width: 62px">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>
                <div class="grid-col segundol" id="segundol">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">Nivel Logro</p>
                        <p class="head">II SEM</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item sem nivel_sem2" name="<?php echo $c['idAlumnosActual']; ?>">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>
                <div class="grid-col segundon" id="segundon">
                    <div class="grid-item grid-item--header" style="background-color: #11b106;">
                        <p class="head">Nota Final</p>
                        <p class="head">II SEM</p>
                    </div>
                    <?php foreach ($this->alumnos as $c) : ?>
                        <div class="grid-item sem nota_final_sem2" name="<?php echo $c['idAlumnosActual']; ?>">
                        </div>
                    <?php endforeach; ?>
                    <div id="alum" name="totalesheader" class="grid-item"
                         style="text-align: center; width: auto; height: 80px">
                        <p></p>
                    </div>
                </div>

            </div>
        </div>


        <?php

    }

//Inicio Laguna
} else if ($id_establecimiento == 8) {

    $codigos = new Zend_Session_Namespace('codigo');
    $codigo = $codigos->codigo;

    if ($codigo == 10) {
        ?>
        <link href="<?php echo $this->baseUrl; ?>/css/monitoreolagunapre.css" type="text/css" rel="stylesheet"/>
        <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreolagunapre.js"></script>
    <?php } else { ?>

        <link href="<?php echo $this->baseUrl; ?>/css/monitoreolaguna.css" type="text/css" rel="stylesheet"/>
        <script src="<?php echo $this->baseUrl; ?>/javascript/monitoreolaguna.js"></script>
    <?php } ?>


    <?php if ($this->messages) {
        ?>

        <div class="error">
            <p>
                <?php foreach ($this->messages as $msg): ?>
                    <?php echo $msg; ?>
                <?php endforeach; ?>


            </p>

        </div>
        <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
            'action' => 'index'), null, true);
        ?>"><i class="icon-hand-left"></i> Volver</a>
    <?php } else {


        ?>

        <?php
        $nombrecurso = new Zend_Session_Namespace('nombre_curso');
        $nombre_curso = $nombrecurso->nombre_curso;

        $idcurso = new Zend_Session_Namespace('id_curso');
        $id_curso = $idcurso->id_curso;

        $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
        $id_detalle_curso = $iddetallecurso->id_detalle_curso;

        $cargo = new Zend_Session_NameSpace("cargo");

        $ingreson = new Zend_Session_Namespace('ingresonota');
        $ingresonota = $ingreson->ingresonota;


        if ($cargo->cargo == '2') { ?>

            <?php
            $nivelcurso = new Zend_Session_Namespace('nivel_curso');
            $nivel_curso = $nivelcurso->nivel_curso; ?>

            <a class="button medium " href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

        <?php
        }
        if ($cargo->cargo == '1' || $cargo->cargo == '3') { ?>
            <a class="button medium blue" href="<?php echo $this->url(array('controller' => 'Libro',
                'action' => 'abrir', 'id' => $id_curso), null, TRUE);
            ?>"><i class="icon-hand-left"></i> Volver</a>

        <?php } ?>

        <input type="hidden" id="apx" value="<?php echo $this->aprox; ?>">

        <div class="center-header">
            <div style="width: 40%">
                <?php if ($cargo->cargo == '2') {
                    if ($codigo != 10) {
                        ?>


                        <div class="ventana"><a class="button medium blue" id="nuevo"
                                                href="<?php echo $this->url(array('controller' => 'Libro',
                                                    'action' => 'agregarguialag', 'id' => ''), null, TRUE);
                                                ?>"> Nueva Evaluación</a></div>

                    <?php } else { ?>
                        <div class="ventana"><a class="button medium blue" id="nuevo"
                                                href="<?php echo $this->url(array('controller' => 'Libro',
                                                    'action' => 'agregarguialagpre', 'id' => ''), null, TRUE);
                                                ?>"> Nueva Evaluación</a></div>

                        <div style="margin-top: 8%; margin-bottom: 7%;" class="center">
                            <h4>

                                <?php
                                if ($codigo == 10) {

                                    ?>
                                    <label for="ambito" class="required">Mostrar Núcleos por Ambito: </label>
                                    <select name="idAmbito" style="width: 260px;" id="sltAmbito">
                                        <?php


                                        foreach ($this->listaambitos as $ambito) : ?>

                                            <option value="<?php echo $ambito['idAmbito']; ?>"><?php echo $ambito['nombreAmbito']; ?></option>
                                        <?php
                                        endforeach;

                                        ?>
                                    </select>
                                    <?php

                                }

                                ?>
                            </h4>
                        </div>

                    <?php }
                } ?>
            </div>
            <div style="width: 60%">
                <h3>Curso: <?php echo $nombre_curso; ?></h3>
            </div>

        </div>


        <ul class="tabs left" id="listas">
            <?php
            if ($codigo != 10) {
                foreach ($this->listaasignatura as $c) : ?>

                    <li><a class="asignatura" href="#" id="<?php echo $c['idAsignatura']; ?>"
                           name="<?php echo $c['tipoAsignatura']; ?>"><?php echo $c['nombreAsignatura']; ?></a></li>


                <?php endforeach;
            } else {

                foreach ($this->listaasignatura as $c) :?>

                    <li id="<?php echo $c['idAmbito']; ?>" class="asignaturali">
                        <a class="asignatura" href="#" id="<?php echo $c['idNucleo']; ?>" data-pre="true"
                           name="<?php echo $c['tipoAsignatura']; ?>"
                           data-idAmbito="<?php echo $c['idAmbito']; ?>"><?php echo $c['nombreNucleo']; ?>
                        </a>
                    </li>
                <?php
                endforeach;
            }
            ?>
        </ul>
        <input type="hidden" id="us" value="<?php echo $cargo->cargo; ?>">


        <?php
        if ($codigo == 10) {
            ?>

            <div class="grid-container" id="tblTabla">
                <div class="grid">
                    <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                        <div class="grid-item grid-item--header">
                            <p class="head">Alumnos</p>
                        </div>
                        <?php foreach ($this->alumnos as $c) : ?>
                            <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                                 style="text-align: left; width: auto;">
                                <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                            </div>
                        <?php endforeach; ?>


                    </div>


                    <div class="grid-col primer" id="primer">
                        <div class="grid-item grid-item--header" style="background-color: #b4ccce;">
                            <p class="head"></p>
                        </div>
                        <?php foreach ($this->alumnos as $c) : ?>
                            <div class="grid-item sem" style="background-color: #b4ccce">
                            </div>
                        <?php endforeach; ?>
                    </div>

                    <div class="grid-col segundo" id="segundo" style="display: none">
                        <div class="grid-item grid-item--header" style="background-color: #b4ccce;">
                            <p class="head"></p>
                        </div>
                        <?php foreach ($this->alumnos as $c) : ?>
                            <div class="grid-item sem" style="background-color: #b4ccce">
                            </div>
                        <?php endforeach; ?>
                    </div>

                </div>
            </div>

        <?php } else { ?>

            <div class="grid-container" id="tblTabla">
                <div class="grid">
                    <div class="grid-col grid-col--fixed-left alumnos" id="alumnos">
                        <div class="grid-item grid-item--header">
                            <p class="head">Alumnos</p>
                        </div>
                        <?php foreach ($this->alumnos as $c) : ?>
                            <div id="alum" name="<?php echo $c['idAlumnosActual']; ?>" class="grid-item"
                                 style="text-align: left; width: auto;">
                                <p><?php echo $c['apaterno'] . ' ' . $c['amaterno'] . ' ' . $c['nombres']; ?> </p>
                            </div>
                        <?php endforeach; ?>


                    </div>

                    <?php if ($idtevalucacion == 1) { ?>

                        <div class="grid-col primer" id="primer">
                            <div class="grid-item grid-item--header" style="background-color: #11b106;">
                                <p class="head">I SEM</p>
                            </div>
                            <?php foreach ($this->alumnos as $c) : ?>
                                <div class="grid-item sem">
                                </div>
                            <?php endforeach; ?>
                        </div>


                        <div class="grid-col segundo" id="segundo">
                            <div class="grid-item grid-item--header" style="background-color: #11b106;">
                                <p class="head">II SEM</p>
                            </div>
                            <?php foreach ($this->alumnos as $c) : ?>
                                <div class="grid-item sem">
                                </div>
                            <?php endforeach; ?>
                        </div>

                    <?php } else { ?>

                        <div class="grid-col primert" id="primert">
                            <div class="grid-item grid-item--header" style="background-color: #11b106;">
                                <p class="head">I TRIM</p>
                            </div>
                            <?php foreach ($this->alumnos as $c) : ?>
                                <div class="grid-item sem">
                                </div>
                            <?php endforeach; ?>
                        </div>


                        <div class="grid-col segundot" id="segundot">
                            <div class="grid-item grid-item--header" style="background-color: #11b106;">
                                <p class="head">II TRIM</p>
                            </div>
                            <?php foreach ($this->alumnos as $c) : ?>
                                <div class="grid-item sem">
                                </div>
                            <?php endforeach; ?>
                        </div>

                        <div class="grid-col tercerot" id="tercerot">
                            <div class="grid-item grid-item--header" style="background-color: #11b106;">
                                <p class="head">III TRIM</p>
                            </div>
                            <?php foreach ($this->alumnos as $c) : ?>
                                <div class="grid-item sem">
                                </div>
                            <?php endforeach; ?>
                        </div>

                    <?php } ?>


                    <div class="grid-col grid-col--fixed-right " id="final">
                        <div class="grid-item grid-item--header final" style="background-color: #63abe6;">
                            <p class="head">FINAL</p>
                        </div>
                        <?php foreach ($this->alumnos as $c) : ?>
                            <div class="grid-item final">
                            </div>
                        <?php endforeach; ?>
                    </div>

                </div>
            </div>


        <?php }
        ?>


        <?php

    }


} else if ($id_establecimiento == 6) {

    $codigos = new Zend_Session_Namespace('codigo');
    $codigo = $codigos->codigo;

    $nombrecurso = new Zend_Session_Namespace('nombre_curso');
    $nombre_curso = $nombrecurso->nombre_curso;

    $idcurso = new Zend_Session_Namespace('id_curso');
    $idCurso = $idcurso->id_curso;

    $iddetallecurso = new Zend_Session_Namespace('id_detalle_curso');
    $id_detalle_curso = $iddetallecurso->id_detalle_curso;

    $cargos = new Zend_Session_NameSpace("cargo");
    $rol = $cargos->cargo;

    $ingreson = new Zend_Session_Namespace('ingresonota');
    $ingresonota = $ingreson->ingresonota;

    $nivelcurso = new Zend_Session_Namespace('nivel_curso');
    $nivel_curso = $nivelcurso->nivel_curso;


    $periodo = new Zend_Session_Namespace('periodo');
    $idPeriodo = $periodo->periodo;

    if ($idPeriodo == 55) {

    ?>
    <div id="nota-chocota-2022">
        <div v-if="codigo === 110" >

            <div class="d-flex justify-content-left">
                <b-button
                    class="button medium"
                    href="<?php echo $this->url(array('controller' => 'Libro',
                        'action' => 'abrir', 'id' => $idCurso), null, TRUE);?>"
                >
                    <i class="icon-hand-left"></i>
                    Volver a Libro
                </b-button>

                <!-- NUEVA NOTA -->
                <!-- <btn-modal
                    class="text-center ml-2"
                    clases="btn green"
                    tipo="Crear"
                    texto="Nota"
                    nombre_modal="modal-create-nota"
                /> -->

                <b-button
                    class="button medium blue ml-2"
                    :title="'Ir a Evaluaciones Formativas de '+nombreAsignaturaSelected"
                    @click="goToGuiaFormativa(idAsignaturaSelected, nombreAsignaturaSelected)"
                >
                    <i class="icon-hand-up"></i>
                    Evaluaciones Formativas
                </b-button>

                <!-- NUEVA EVALUACIÓN -->
                <btn-modal
                    class="text-center ml-2"
                    clases="btn green"
                    tipo="Crear"
                    texto="Evaluación Sumativa"
                    nombre_modal="modal-create-evaluacion"
                />

            </div>

            <div>
                <!--
                    TODO: IMPORTANTE!
                    EL modal se puso en un div distinto de su btn,
                    ya que no se mostraba estando en el mismo div
                -->
                <!-- <nota-create
                    v-if="idAsignaturaSelected !== null"
                    modulo="Nota"
                    nombre_modal="modal-create-nota"
                    :id_tipo_evaluacion="idTipoEvalucacion"
                    :id_asignatura_selected="idAsignaturaSelected"
                    :id_curso="idCurso"
                    :nombre_asignatura="nombreAsignaturaSelected"
                    :id_periodo="idPeriodo"
                /> -->
                <!--
                    TODO: IMPORTANTE!
                    EL modal se puso en un div distinto de su btn,
                    ya que no se mostraba estando en el mismo div
                -->
                <evaluacion-create
                    v-if="idAsignaturaSelected !== null"
                    modulo="Evaluación"
                    nombre_modal="modal-create-evaluacion"
                    tipo_evaluacion="Sumativa"
                    :id_tipo_evaluacion="idTipoEvalucacion"
                    :id_asignatura_selected="idAsignaturaSelected"
                    :id_curso="idCurso"
                    :nombre_asignatura="nombreAsignaturaSelected"
                    :id_periodo="idPeriodo"
                    :id_evaluacion="Number(idEvaluacion)"
                />
            </div>

            <div>
                <!-- TITULO -->
                <h4 class="text-left mt-3 mb-4">Monitoreo: <?php echo $nombre_curso ?></h4>
            </div>

            <div class="mt-4">
                <b-tabs
                    content-class="p-0"
                    v-model="tabAsignatura"
                >
                    <b-tab
                        v-for="(asignatura, index) in asignaturas"
                        v-bind:key="index"
                        :value="asignatura.idAsignatura"
                        :title="asignatura.nombreAsignatura"
                        :active="index == 0"
                    >

                        <nota
                            v-if="alumnosCurso && idAsignaturaSelected !== null"
                            :alumnos_curso="alumnosCurso"
                            :id_tipo_evaluacion="idTipoEvalucacion"
                            :id_asignatura="asignatura.idAsignatura"
                            :id_periodo="idPeriodo"
                            :id_curso="idCurso"
                            :id_asignatura_selected="idAsignaturaSelected"
                            :nombre_asignatura="nombreAsignaturaSelected"
                        />

                    </b-tab>
                </b-tabs>
            </div>

        </div>
        <div v-else >
            <!--<div class="d-flex justify-content-left">
                <a
                    class="button medium"
                    href="<?php echo $this->url(array('controller' => 'Libro',
                        'action' => 'abrir', 'id' => $id_curso), null, TRUE);?>"
                >
                    <i class="icon-hand-left"></i>
                    Volver
                </a>
                 <monitoreo-pre
                    v-if="alumnosCurso"
                    :alumnos_curso="alumnosCurso"
                />
            </div>-->
        </div>

    </div>

    <script>

        new Vue({
            el: "#nota-chocota-2022",
            alumnos,
            evaluaciones,
            notas,
            index,
            data: {
                idPeriodo: <?php echo $idPeriodo ?>,
                idCurso: <?php echo $idCurso ?>,
                idTipoEvalucacion: <?php echo $idtevalucacion ?>,
                codigo: <?php echo $codigo ?>,
                rol: <?php echo $rol ?>,
                idEvaluacion: "<?php echo $this->id_evaluacion ?>",
                tabAsignatura: null,
                idAsignaturaSelected: null,
                nombreAsignaturaSelected: null,
                asignaturas: [],
                alumnosCurso: [],
                data: [],
            },
            computed: {
            },
            watch: {
                tabAsignatura() {
                    this.changeAsignatura()
                },
            },
            created() {
                <?php
                    $largoAlumnos = count($this->alumnos);
                    for ($i = 0; $i < $largoAlumnos; $i++) {
                        $alumno = $this->alumnos[$i];
                ?>
                        this.setAlumnos('<?php echo json_encode($alumno)?>')
                <?php
                    }
                    $largoAsignaturas = count($this->listaasignatura);
                    for ($a = 0; $a < $largoAsignaturas; $a++) {
                        $asignatura = $this->listaasignatura[$a];
                ?>
                        this.setAsignaturas('<?php echo json_encode($asignatura)?>')
                <?php
                    }
                // ?>
                this.setData(<?php echo $idPeriodo ?>, <?php echo $idCurso ?>)
                evaluaciones.dispatch('fetchEvaluacionesCurso', this.data[0])
                notas.dispatch('fetchNotas', this.data[0])
            },
            methods: {
                ...Vuex.mapActions([{ fetchEvaluacionesCurso: 'evaluaciones/fetchEvaluacionesCurso' }]),
                ...Vuex.mapActions([{ fetchNotas: 'notas/fetchNotas' }]),
                goToGuiaFormativa(idAsignaturaSelected, nombreAsignaturaSelected) {
                    const baseUrl = index.getters.api
                    console.log('nombreAsignaturaSelected :', nombreAsignaturaSelected)
                    const data = `?idAsignaturaSelected=${idAsignaturaSelected}&nombreAsignaturaSelected=${nombreAsignaturaSelected}`
                    window.location.href = baseUrl+'Monitoreo/chocotaabrirformativa/'+data;
                },
                setAsignaturas(asignatura) {
                    const asignaturaPush = JSON.parse(asignatura);
                    this.asignaturas.push(asignaturaPush)
                },
                setAlumnos(alumno) {
                    const alumnoPush = JSON.parse(alumno);
                    this.alumnosCurso.push(alumnoPush)
                },
                changeAsignatura() {
                    this.idAsignaturaSelected = this.asignaturas[this.tabAsignatura]['idAsignatura']
                    this.nombreAsignaturaSelected = this.asignaturas[this.tabAsignatura]['nombreAsignatura']
                },
                setData(idPeriodo, idCurso) {
                    this.data.push({
                        idPeriodo,
                        idCurso,
                    })
                },
            },
        })
    </script>
    <?php
    } else {
    ?>
    <div id="nota-chocota-2021">
        <div v-if="codigo === 110" >

            <div class="d-flex justify-content-left">
                <b-button
                    class="button medium"
                    href="<?php echo $this->url(array('controller' => 'Libro',
                        'action' => 'abrir', 'id' => $idCurso), null, TRUE);?>"
                >
                    <i class="icon-hand-left"></i>
                    Volver a Libro
                </b-button>

                <!-- NUEVA NOTA -->
                <btn-modal
                    class="text-center ml-2"
                    clases="btn green"
                    tipo="Crear"
                    texto="Nota"
                    nombre_modal="modal-create-nota"
                />

            </div>

            <div>
                <!--
                    TODO: IMPORTANTE!
                    EL modal se puso en un div distinto de su btn,
                    ya que no se mostraba estando en el mismo div
                -->
                <nota-create
                    v-if="idAsignaturaSelected !== null"
                    modulo="Nota"
                    nombre_modal="modal-create-nota"
                    :id_tipo_evaluacion="idTipoEvalucacion"
                    :id_asignatura_selected="idAsignaturaSelected"
                    :id_curso="idCurso"
                    :nombre_asignatura="nombreAsignaturaSelected"
                    :id_periodo="idPeriodo"
                />
                <!--
                    TODO: IMPORTANTE!
                    EL modal se puso en un div distinto de su btn,
                    ya que no se mostraba estando en el mismo div
                -->
                <evaluacion-create
                    v-if="tabAsignatura !== null"
                    modulo="Evaluación"
                    nombre_modal="modal-create-evaluacion"
                    tipo_evaluacion="Sumativa"
                    :id_tipo_evaluacion="idTipoEvalucacion"
                    :id_asignatura_selected="idAsignaturaSelected"
                    :id_curso="idCurso"
                    :nombre_asignatura="nombreAsignaturaSelected"
                    :id_periodo="idPeriodo"
                    :id_evaluacion="Number(idEvaluacion)"
                />
            </div>

            <div>
                <!-- TITULO -->
                <h4 class="text-left mt-3 mb-4">Monitoreo: <?php echo $nombre_curso ?></h4>
            </div>

            <div class="mt-4">
                <b-tabs
                    content-class="p-0"
                    v-model="tabAsignatura"
                >
                    <b-tab
                        v-for="(asignatura, index) in asignaturas"
                        v-bind:key="index"
                        :value="asignatura.idAsignatura"
                        :title="asignatura.nombreAsignatura"
                        :active="index == 0"
                    >

                        <nota
                            v-if="alumnosCurso && idAsignaturaSelected !== null"
                            :alumnos_curso="alumnosCurso"
                            :id_tipo_evaluacion="idTipoEvalucacion"
                            :id_asignatura="asignatura.idAsignatura"
                            :id_periodo="idPeriodo"
                            :id_curso="idCurso"
                            :id_asignatura_selected="idAsignaturaSelected"
                            :nombre_asignatura="nombreAsignaturaSelected"
                        />

                    </b-tab>
                </b-tabs>
            </div>

        </div>
        <div v-else >
            <!--<div class="d-flex justify-content-left">
                <a
                    class="button medium"
                    href="<?php echo $this->url(array('controller' => 'Libro',
                        'action' => 'abrir', 'id' => $id_curso), null, TRUE);?>"
                >
                    <i class="icon-hand-left"></i>
                    Volver
                </a>
                 <monitoreo-pre
                    v-if="alumnosCurso"
                    :alumnos_curso="alumnosCurso"
                />
            </div>-->
        </div>

    </div>

    <script>

        new Vue({
            el: "#nota-chocota-2021",
            alumnos,
            evaluaciones,
            notas,
            index,
            data: {
                idPeriodo: <?php echo $idPeriodo ?>,
                idCurso: <?php echo $idCurso ?>,
                idTipoEvalucacion: <?php echo $idtevalucacion ?>,
                codigo: <?php echo $codigo ?>,
                rol: <?php echo $rol ?>,
                idEvaluacion: "<?php echo $this->id_evaluacion ?>",
                tabAsignatura: null,
                idAsignaturaSelected: null,
                nombreAsignaturaSelected: null,
                asignaturas: [],
                alumnosCurso: [],
                data: [],
            },
            computed: {
            },
            watch: {
                tabAsignatura() {
                    this.changeAsignatura()
                },
            },
            created() {
                <?php
                    $largoAlumnos = count($this->alumnos);
                    for ($i = 0; $i < $largoAlumnos; $i++) {
                        $alumno = $this->alumnos[$i];
                ?>
                        this.setAlumnos('<?php echo json_encode($alumno)?>')
                <?php
                    }
                    $largoAsignaturas = count($this->listaasignatura);
                    for ($a = 0; $a < $largoAsignaturas; $a++) {
                        $asignatura = $this->listaasignatura[$a];
                ?>
                        this.setAsignaturas('<?php echo json_encode($asignatura)?>')
                <?php
                    }
                // ?>
                this.setData(<?php echo $idPeriodo ?>, <?php echo $idCurso ?>)
                evaluaciones.dispatch('fetchEvaluacionesCurso', this.data[0])
                notas.dispatch('fetchNotas', this.data[0])
            },
            methods: {
                ...Vuex.mapActions([{ fetchEvaluacionesCurso: 'evaluaciones/fetchEvaluacionesCurso' }]),
                ...Vuex.mapActions([{ fetchNotas: 'notas/fetchNotas' }]),
                setAsignaturas(asignatura) {
                    const asignaturaPush = JSON.parse(asignatura);
                    this.asignaturas.push(asignaturaPush)
                },
                setAlumnos(alumno) {
                    const alumnoPush = JSON.parse(alumno);
                    this.alumnosCurso.push(alumnoPush)
                },
                changeAsignatura() {
                    this.idAsignaturaSelected = this.asignaturas[this.tabAsignatura]['idAsignatura']
                    this.nombreAsignaturaSelected = this.asignaturas[this.tabAsignatura]['nombreAsignatura']
                },
                setData(idPeriodo, idCurso) {
                    this.data.push({
                        idPeriodo,
                        idCurso,
                    })
                },
            },
        })
    </script>
    <?php
    }
    ?>
    <style>
        input.transparent-input{
            background-color:transparent !important;
            border:none !important;
            border-bottom: 1px solid! important;
        }
    </style>

        <!-- bootstrap -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <?php
}
